export const STORY_ARCHIVE = 'STORY_ARCHIVE';

export const STORIES_FETCH = 'STORIES_FETCH';
export const STORIES_ADD = 'STORIES_ADD';
export const STORIES_FETCH_ERROR = 'STORIES_FETCH_ERROR';

export const TODO_ADD = 'TODO_ADD';
export const TODO_TOGGLE = 'TODO_TOGGLE';
export const TODO_SET_FILTER = 'TODO_SET_FILTER';
export const TODO_SHOW_COMPLETED = 'TODO_SHOW_COMPLETED';
export const TODO_SHOW_INCOMPLETE = 'TODO_SHOW_INCOMPLETE';

export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
